/* automatically generated by rust-bindgen 0.59.1 */

pub const INFINITE_TIME: u32 = 4294967295;
pub type handle_t = i32;
pub const IPC_PORT_ALLOW_TA_CONNECT: trusty_sys::c_uint = 1;
pub const IPC_PORT_ALLOW_NS_CONNECT: trusty_sys::c_uint = 2;
pub type _bindgen_ty_1 = trusty_sys::c_uint;
pub const IPC_CONNECT_WAIT_FOR_PORT: trusty_sys::c_uint = 1;
pub const IPC_CONNECT_ASYNC: trusty_sys::c_uint = 2;
pub type _bindgen_ty_2 = trusty_sys::c_uint;
pub const IPC_HANDLE_POLL_NONE: trusty_sys::c_uint = 0;
pub const IPC_HANDLE_POLL_READY: trusty_sys::c_uint = 1;
pub const IPC_HANDLE_POLL_ERROR: trusty_sys::c_uint = 2;
pub const IPC_HANDLE_POLL_HUP: trusty_sys::c_uint = 4;
pub const IPC_HANDLE_POLL_MSG: trusty_sys::c_uint = 8;
pub const IPC_HANDLE_POLL_SEND_UNBLOCKED: trusty_sys::c_uint = 16;
pub type _bindgen_ty_3 = trusty_sys::c_uint;
